=== monster-penguin/retrobios/bios/Arcade/MAME/hash/softwarelist.dtd
<!ELEMENT softwarelist (notes?, software+)>
	<!ATTLIST softwarelist name CDATA #REQUIRED>
	<!ATTLIST softwarelist description CDATA #IMPLIED>
	<!ELEMENT notes (#PCDATA)>
	<!ELEMENT software (description, year, publisher, notes?, info*, sharedfeat*, part*)>
		<!ATTLIST software name CDATA #REQUIRED>
		<!ATTLIST software cloneof CDATA #IMPLIED>
		<!ATTLIST software supported (yes|partial|no) "yes">
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT publisher (#PCDATA)>
		<!ELEMENT info EMPTY>
			<!ATTLIST info name CDATA #REQUIRED>
			<!ATTLIST info value CDATA #IMPLIED>
		<!ELEMENT sharedfeat EMPTY>
			<!ATTLIST sharedfeat name CDATA #REQUIRED>
			<!ATTLIST sharedfeat value CDATA #IMPLIED>
		<!ELEMENT part (feature*, dataarea*, diskarea*, dipswitch*)>
			<!ATTLIST part name CDATA #REQUIRED>
			<!ATTLIST part interface CDATA #REQUIRED>
			<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
			<!ELEMENT feature EMPTY>
				<!ATTLIST feature name CDATA #REQUIRED>
				<!ATTLIST feature value CDATA #IMPLIED>
			<!ELEMENT dataarea (rom*)>
				<!ATTLIST dataarea name CDATA #REQUIRED>
				<!ATTLIST dataarea size CDATA #REQUIRED>
				<!ATTLIST dataarea width (8|16|32|64) "8">
				<!ATTLIST dataarea endianness (big|little) "little">
				<!ELEMENT rom EMPTY>
					<!ATTLIST rom name CDATA #IMPLIED>
					<!ATTLIST rom size CDATA #IMPLIED>
					<!ATTLIST rom crc CDATA #IMPLIED>
					<!ATTLIST rom sha1 CDATA #IMPLIED>
					<!ATTLIST rom offset CDATA #IMPLIED>
					<!ATTLIST rom value CDATA #IMPLIED>
					<!ATTLIST rom status (baddump|nodump|good) "good">
					<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue|reload_plain|ignore) #IMPLIED>
			<!ELEMENT diskarea (disk*)>
				<!ATTLIST diskarea name CDATA #REQUIRED>
				<!ELEMENT disk EMPTY>
					<!ATTLIST disk name CDATA #REQUIRED>
					<!ATTLIST disk sha1 CDATA #IMPLIED>
					<!ATTLIST disk status (baddump|nodump|good) "good">
					<!ATTLIST disk writeable (yes|no) "no">
			<!ELEMENT dipswitch (dipvalue*)>
				<!ATTLIST dipswitch name CDATA #REQUIRED>
				<!ATTLIST dipswitch tag CDATA #REQUIRED>
				<!ATTLIST dipswitch mask CDATA #REQUIRED>
				<!ELEMENT dipvalue EMPTY>
					<!ATTLIST dipvalue name CDATA #REQUIRED>
					<!ATTLIST dipvalue value CDATA #REQUIRED>
					<!ATTLIST dipvalue default (yes|no) "no">

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/leapfrog_zippity_cart.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<!--
    Not dumped:

    Toy Story 3

    (it also needs confirming if US / UK cartridges are different, dumps are all from UK cartridges)

-->
<softwarelist name="leapfrog_zippity_cart" description="LeapFrog Zippity cartridges">

	<software name="prinfrog" supported="no">
		<description>The Princess and the Frog - Magical Bayou Adventure (UK)</description>
		<year>2009</year>
		<publisher>LeapFrog</publisher>
		<info name="serial" value="500-13779-A" />
		<part name="cart" interface="leapfrog_zippity_cart">
			<dataarea name="rom" size="0x4200000">
				<rom name="500-13779-A - The Princess and the Frog - Magical Bayou Adventure.bin" size="0x4200000" crc="f41715d0" sha1="c6654f021ac0b12fecb056f1d21058957a6e1e30" />
			</dataarea>
		</part>
	</software>

	<software name="cars" supported="no">
		<description>The World of Cars - Driven to Learn (UK)</description>
		<year>2009</year>
		<publisher>LeapFrog</publisher>
		<info name="serial" value="500-13589-B" />
		<part name="cart" interface="leapfrog_zippity_cart">
			<dataarea name="rom" size="0x4200000">
				<rom name="500-13589-B - The World of Cars - Driven to Learn.bin" size="0x4200000" crc="f52e613e" sha1="81da432cbdf6f80ac1a42656978d4027b50e0587" />
			</dataarea>
		</part>
	</software>

	<software name="disprin" supported="no">
		<description>Disney Princess - Magical Movement &amp; Learning (UK)</description>
		<year>2009</year>
		<publisher>LeapFrog</publisher>
		<info name="serial" value="500-13590-A" />
		<part name="cart" interface="leapfrog_zippity_cart">
			<dataarea name="rom" size="0x4200000">
				<rom name="500-13590-A - DisneyPrincess - Magical Movement &amp; Learning.bin" size="0x4200000" crc="d060a223" sha1="00f454b629d7bcc7f58a43dd453d410a8ed60a99" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/mz2200_cass.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<softwarelist name="mz2200_cass" description="Sharp MZ-2200 cassettes">

	<software name="cnonball">
		<description>Cannon Ball</description>
		<year>1983</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="WB-1001"/>
		<info name="alt_title" value="キャノンボール"/>
		<part name="cass1" interface="mz_cass">
			<dataarea name="cass" size="1386284">
				<rom name="wb-1001.wav" size="1386284" crc="461ce2f5" sha1="8d859095b18ac5aab348a205f3734340e6b5290b" />
			</dataarea>
		</part>
	</software>

	<software name="vegecrsh">
		<description>Vegetable Crash</description>
		<year>1983</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="WB-1002"/>
		<info name="alt_title" value="ベジタブルクラッシュ"/>
		<part name="cass1" interface="mz_cass">
			<dataarea name="cass" size="1233964">
				<rom name="wb-1002.wav" size="1233964" crc="953f5d0e" sha1="527f9bfef1fd0a923ce982ef971602c86820c26b" />
			</dataarea>
		</part>
	</software>

	<software name="bombrman">
		<description>Bomber Man</description>
		<year>1983</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="WB-1003"/>
		<info name="alt_title" value="爆弾男"/>
		<part name="cass1" interface="mz_cass">
			<dataarea name="cass" size="3944464">
				<rom name="wb-1003.wav" size="3944464" crc="da852425" sha1="03c5b8694b7482c6af696fef5338d05c3d86c70e" />
			</dataarea>
		</part>
	</software>

	<software name="powrfail">
		<description>Power Fail</description>
		<year>1983</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="WB-1004"/>
		<info name="alt_title" value="パワーフェイル"/>
		<part name="cass1" interface="mz_cass">
			<dataarea name="cass" size="2145580">
				<rom name="wb-1004.wav" size="2145580" crc="eecf0e2a" sha1="8263a0ba92c6e9f3d94fed0d7005591841d4d826" />
			</dataarea>
		</part>
	</software>

	<software name="hiyokof">
		<description>Hiyoko Fighter</description>
		<year>1983</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="WB-1005"/>
		<info name="alt_title" value="ヒヨコファイター"/>
		<part name="cass1" interface="mz_cass">
			<dataarea name="cass" size="1566764">
				<rom name="wb-1005.wav" size="1566764" crc="08c2d4a3" sha1="1325773c7f640c1f86186c1d5608cdff7995d007" />
			</dataarea>
		</part>
	</software>

	<software name="thespidr">
		<description>The Spider</description>
		<year>1983</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="WB-1006"/>
		<info name="alt_title" value="ザ・スパイダー"/>
		<part name="cass1" interface="mz_cass">
			<dataarea name="cass" size="3149100">
				<rom name="wb-1006.wav" size="3149100" crc="eec8674f" sha1="231d55c6cbb48fe88676fec31f014c6002788b5f" />
			</dataarea>
		</part>
	</software>

	<software name="hitsujai">
		<description>Hitsuja~i!</description>
		<year>1983</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="WB-1007"/>
		<info name="alt_title" value="ひつじゃ～い!"/>
		<part name="cass1" interface="mz_cass">
			<dataarea name="cass" size="1887532">
				<rom name="wb-1007.wav" size="1887532" crc="6fc27604" sha1="d3031ad40cb5c4bfc4a7afd8ddd7a16bbf345e70" />
			</dataarea>
		</part>
	</software>

	<software name="mj05">
		<description>MJ-05</description>
		<year>1983</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="WB-1008"/>
		<part name="cass1" interface="mz_cass">
			<dataarea name="cass" size="6366398">
				<rom name="wb-1008.wav" size="6366398" crc="d7335aad" sha1="a26dd12e064b02d18ba673bb4633762aa38cca09" />
			</dataarea>
		</part>
	</software>

	<software name="help">
		<description>Help!</description>
		<year>1983</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="WB-1009"/>
		<part name="cass1" interface="mz_cass">
			<dataarea name="cass" size="1489708">
				<rom name="wb-1009.wav" size="1489708" crc="523985e0" sha1="f4a0f20d698caf5dd597ea17b59e5a351f49f1f2" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/mpf1_rom.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<softwarelist name="mpf1_rom" description="Micro-Professor 1 ROMs">

	<!-- Micro-Professor 1 -->

	<software name="basic">
		<description>BASIC-MPF</description>
		<year>1981</year>
		<publisher>Multitech</publisher>
		<info name="usage" value="ADDR 2000 GO"/>
		<sharedfeat name="compatibility" value="IA"/>
		<part name="rom" interface="mpf1_rom">
			<dataarea name="rom" size="2048">
				<rom name="basic-mpf.bin" size="2048" crc="73ac279f" sha1="36271201266ee7f6435c46cf41bc2ef9f77505b6"/>
			</dataarea>
		</part>
	</software>

	<software name="hex">
		<description>Hex Download Program</description>
		<year>19??</year>
		<publisher>Flite Electronics</publisher>
		<info name="usage" value="ADDR 2000 GO"/>
		<sharedfeat name="compatibility" value="IB"/>
		<part name="rom" interface="mpf1_rom">
			<dataarea name="rom" size="4096">
				<rom name="hex-1bp.bin" size="4096" crc="7c1b6534" sha1="6bb56f96f38699cd88e613368f6fc5076fb00c64"/>
			</dataarea>
		</part>
	</software>

	<!-- Micro-Professor 1P -->

	<software name="basic_ip">
		<description>BASIC-IP</description>
		<year>1983</year>
		<publisher>Multitech</publisher>
		<info name="usage" value="CONTROL-B"/>
		<sharedfeat name="compatibility" value="IP"/>
		<part name="rom" interface="mpf1_rom">
			<dataarea name="rom" size="8192">
				<rom name="basic-ip.bin" size="8192" crc="fe9c0f73" sha1="62a15b020be2e95b7b465f96bd63dd6bb1655094"/>
			</dataarea>
		</part>
	</software>

	<software name="forth_ip">
		<description>FORTH-IP</description>
		<year>1983</year>
		<publisher>Multitech</publisher>
		<info name="usage" value="CONTROL-B"/>
		<sharedfeat name="compatibility" value="IP"/>
		<part name="rom" interface="mpf1_rom">
			<dataarea name="rom" size="8192">
				<rom name="forth-ip.bin" size="8192" crc="459a1715" sha1="4e62817885cb7262557c5da4765e75c371ee81b8"/>
			</dataarea>
		</part>
	</software>

	<!-- Micro-Professor 1/88 -->

	<software name="forth_i88">
		<description>FORTH-I/88</description>
		<year>1985</year>
		<publisher>Multitech</publisher>
		<info name="usage" value="H"/>
		<sharedfeat name="compatibility" value="I88"/>
		<part name="rom" interface="mpf1_rom">
			<dataarea name="rom" size="8192">
				<rom name="forth_i88.bin" size="8192" crc="a04caba9" sha1="1e94f1355722228cd4de0e9a773e7a923cbad745"/>
			</dataarea>
		</part>
	</software>

	<software name="vip_i88">
		<description>VIP-I/88</description>
		<year>1985</year>
		<publisher>Multitech</publisher>
		<info name="usage" value="Z"/>
		<sharedfeat name="compatibility" value="I88"/>
		<part name="rom" interface="mpf1_rom">
			<dataarea name="rom" size="16384">
				<rom name="vip_i88.bin" size="16384" crc="c5aceba3" sha1="735af166ff0dbe9c3e48eec61ab2365be74120cb"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/gj4000.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="gj4000" description="VTech Genius Junior 4000 cartridges">

	<!-- According to the boxart, this is compatible with: Junior 4000/5000 -->
	<software name="wfk" supported="no">
		<description>Wissen für Kinder</description>
		<year>1997</year>
		<publisher>VTech</publisher>
		<info name="serial" value="80-15272" />

		<part name="rom" interface="genius_rom">
			<dataarea name="rom" size="0x20000">
				<rom name="27-6035-00.u2" size="0x20000" crc="8dcaa8c0" sha1="bca46f6cd150632fca79b1c2b524cd8ed1dacf84"/>
			</dataarea>
		</part>
	</software>
</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/mbc55x.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<softwarelist name="mbc55x" description="Sanyo MBC-550 and MBC-555 disk images">

	<software name="msdos211">
		<description>MS-DOS v2.11</description>
		<year>198?</year>
		<publisher>Sanyo / Microsoft</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="microsoft ms-dos 2.11 (sanyo).img" size="368640" crc="b64b0c3c" sha1="35a9a1e62ccefa3c66d912b4d58c1a132cd757d2" status="baddump" />
			</dataarea>
		</part>
	</software>

	<software name="msdos211a" cloneof="msdos211">
		<description>MS-DOS v2.11 (Alt?)</description>
		<year>198?</year>
		<publisher>Sanyo / Microsoft</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_ms-dos_2.11.ima" size="368640" crc="ab9dd1d4" sha1="eb5a5dd025e0e8efacea603daf37243986d92262"/>
			</dataarea>
		</part>
	</software>

	<software name="msdos125">
		<description>MS-DOS v1.25</description>
		<year>198?</year>
		<publisher>Sanyo / Microsoft</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="163840">
				<rom name="msdos125" size="163840" crc="1ea744cc" sha1="dd8b41bb67d0b888cd70ded4b61701708caa5dac"/>
			</dataarea>
		</part>
	</software>

	<software name="calcstar">
		<description>Calcstar</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_calcstar.ima" size="368640" crc="422ff754" sha1="4d09a213d4a0dd2bdb26398beaed9bce070abbcd"/>
			</dataarea>
		</part>
	</software>

	<software name="datastar">
		<description>Datastar</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_datastar.ima" size="368640" crc="93cad6c5" sha1="5e4ba8deb3995c57e37eda9f06841daff15b0e17"/>
			</dataarea>
		</part>
	</software>

	<software name="easydraw">
		<description>Easy Draw</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_easydraw.ima" size="368640" crc="e6c1ad15" sha1="d1e392b04a966264114d7965fd18a0a4742fa85c"/>
			</dataarea>
		</part>
	</software>

	<software name="larn">
		<description>Larn</description>
		<year>1986</year>
		<publisher>Noah Morgan</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="larn.img" size="368640" crc="a57add87" sha1="696a0fb800d89d59a22381ddd399f1548fbd3646"/>
			</dataarea>
		</part>
	</software>

	<software name="picasso">
		<description>Picasso</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="picasso.img" size="368640" crc="b4dad321" sha1="3d5555f5d7d6f49bb51e334c86783611dc131e06"/>
			</dataarea>
		</part>
	</software>

	<software name="spelstar">
		<description>Mailmerge Spelstar</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_mailmerge_spelstar.ima" size="368640" crc="d555bebb" sha1="44de7c054533d5eac7db8802facfda3eea70a1f2"/>
			</dataarea>
		</part>
	</software>

	<software name="rprtstar">
		<description>Reportstar</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_reportstar.ima" size="368640" crc="2992d3a1" sha1="75d589d777c00db7c8364353817947d4ac95c582"/>
			</dataarea>
		</part>
	</software>

	<software name="softse05">
		<description>Soft Sector Disk 05</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="softse05.img" size="368640" crc="a5252da6" sha1="a840d6e2ef9aa840898cd02ec0eca217b1abef3d"/>
			</dataarea>
		</part>
	</software>

	<software name="wordstar">
		<description>Wordstar</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_wordstar.ima" size="368640" crc="71c29f9a" sha1="389215fbfab4c1e218d8ef08fa5f7c2bb2a4e6da"/>
			</dataarea>
		</part>
	</software>



	<software name="basgames">
		<description>Basic Games</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_basic_games.ima" size="368640" crc="e076efa4" sha1="a9fd7dcae96aca09206a4a8529e50cdb191739ba"/>
			</dataarea>
		</part>
	</software>

	<software name="cashman">
		<description>Cashman</description>
		<year>1984</year>
		<publisher>Michtron</publisher>
		<info name="programmer" value="Bill Dunlevy" />
		<info name="release" value="198401xx" />

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="34844">
				<rom name="cashman.td0" size="34844" crc="baecaef3" sha1="0a17be5ea8864e6bc9074acbea39d28a2828d53d"/>
			</dataarea>
		</part>
	</software>

	<software name="demonsd">
		<description>Demon Seed</description>
		<year>1984</year>
		<publisher>Michtron</publisher>
		<info name="programmer" value="Phil Mackenzie &amp; Jeff Sorensen" />

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="29464">
				<rom name="demonsd.td0" size="29464" crc="11d9577b" sha1="15a5927809aa5762a6289386935d1a2c24e8d239"/>
			</dataarea>
		</part>
	</software>

<!-- contains Zork 1, 2 and 3 -->
	<software name="zork">
		<description>Zork Compilation</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="zork.dsk" size="368640" crc="9b7daf44" sha1="34ca63dde2b4a85bac2e6391ca4d588e06058039"/>
			</dataarea>
		</part>
	</software>
</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/psi98.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<softwarelist name="psi98" description="Kontron PSI98 floppy disks">

	<software name="kos605d">
		<description>KOS 6.05D Boot</description>
		<year>1984</year>
		<publisher>Kontron</publisher>
		<info name="usage" value="At the login prompt enter *" />
		<part name="flop1" interface="floppy_5_25">
			<feature name="part_id" value="KOS boot"/>
			<dataarea name="flop" size="518086">
				<rom name="kos605d.td0" size="518086" crc="4b16029c" sha1="bf41cb9e90f2a9b5653cbc6748fe427568099cbd"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<feature name="part_id" value="KOS utils"/>
			<dataarea name="flop" size="545577">
				<rom name="utils605d.td0" size="545577" crc="250c93d7" sha1="f06ae5f75f73cb4d64b2a191dc35d06ecb1f73b3"/>
			</dataarea>
		</part>
	</software>

	<software name="cpm22">
		<description>Kontron CP/M 2.2 V6.31-Z</description>
		<year>1985</year>
		<publisher>Kontron</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="348688">
				<rom name="cpm22.td0" size="348688" crc="731b221e" sha1="55197c410797c11e92d776110b304f21b914a63b"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/cbm8096_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="cbm8096_flop" description="Commodore 8096 diskettes">

	<software name="los96">
		<description>LOS-96</description>
		<year>1981</year>
		<publisher>Commodore</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="174848">
				<rom name="los96disk.d64" size="174848" crc="b78332c5" sha1="744509449b09fae636f47ac47e6496672c2f7ff0" status="baddump" />
			</dataarea>
		</part>
	</software>

	<software name="geckos">
		<description>GeckOS/A65 (v2.0)</description>
		<year>1999</year>
		<publisher>André Fachat</publisher>
		<sharedfeat name="compatibility" value="NTSC,PAL"/>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="174848">
				<rom name="cbm8x96.d64" size="174848" crc="33210394" sha1="ab59246300847b9ccb00b10f220253bae20e76b2"/>
			</dataarea>
		</part>
	</software>

</softwarelist>
