=== monster-penguin/retrobios/bios/Arcade/MAME/hash/softwarelist.dtd
<!ELEMENT softwarelist (notes?, software+)>
	<!ATTLIST softwarelist name CDATA #REQUIRED>
	<!ATTLIST softwarelist description CDATA #IMPLIED>
	<!ELEMENT notes (#PCDATA)>
	<!ELEMENT software (description, year, publisher, notes?, info*, sharedfeat*, part*)>
		<!ATTLIST software name CDATA #REQUIRED>
		<!ATTLIST software cloneof CDATA #IMPLIED>
		<!ATTLIST software supported (yes|partial|no) "yes">
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT publisher (#PCDATA)>
		<!ELEMENT info EMPTY>
			<!ATTLIST info name CDATA #REQUIRED>
			<!ATTLIST info value CDATA #IMPLIED>
		<!ELEMENT sharedfeat EMPTY>
			<!ATTLIST sharedfeat name CDATA #REQUIRED>
			<!ATTLIST sharedfeat value CDATA #IMPLIED>
		<!ELEMENT part (feature*, dataarea*, diskarea*, dipswitch*)>
			<!ATTLIST part name CDATA #REQUIRED>
			<!ATTLIST part interface CDATA #REQUIRED>
			<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
			<!ELEMENT feature EMPTY>
				<!ATTLIST feature name CDATA #REQUIRED>
				<!ATTLIST feature value CDATA #IMPLIED>
			<!ELEMENT dataarea (rom*)>
				<!ATTLIST dataarea name CDATA #REQUIRED>
				<!ATTLIST dataarea size CDATA #REQUIRED>
				<!ATTLIST dataarea width (8|16|32|64) "8">
				<!ATTLIST dataarea endianness (big|little) "little">
				<!ELEMENT rom EMPTY>
					<!ATTLIST rom name CDATA #IMPLIED>
					<!ATTLIST rom size CDATA #IMPLIED>
					<!ATTLIST rom crc CDATA #IMPLIED>
					<!ATTLIST rom sha1 CDATA #IMPLIED>
					<!ATTLIST rom offset CDATA #IMPLIED>
					<!ATTLIST rom value CDATA #IMPLIED>
					<!ATTLIST rom status (baddump|nodump|good) "good">
					<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue|reload_plain|ignore) #IMPLIED>
			<!ELEMENT diskarea (disk*)>
				<!ATTLIST diskarea name CDATA #REQUIRED>
				<!ELEMENT disk EMPTY>
					<!ATTLIST disk name CDATA #REQUIRED>
					<!ATTLIST disk sha1 CDATA #IMPLIED>
					<!ATTLIST disk status (baddump|nodump|good) "good">
					<!ATTLIST disk writeable (yes|no) "no">
			<!ELEMENT dipswitch (dipvalue*)>
				<!ATTLIST dipswitch name CDATA #REQUIRED>
				<!ATTLIST dipswitch tag CDATA #REQUIRED>
				<!ATTLIST dipswitch mask CDATA #REQUIRED>
				<!ELEMENT dipvalue EMPTY>
					<!ATTLIST dipvalue name CDATA #REQUIRED>
					<!ATTLIST dipvalue value CDATA #REQUIRED>
					<!ATTLIST dipvalue default (yes|no) "no">

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/ekara_us.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="ekara_us" description="Takara e-kara (US) cartridges">
	<!-- cartridges contain the ROM only, the XaviX CPU and BIOS are in the base unit -->

	<!-- US cartridges -->

	<!-- e-kara US 5-Songs Starter (US-M001)
	1. "Stronger"                  Britney Spears
	2. "Bye Bye Bye"               *N Sync
	3. "Independent Woman Part 1"  Destiny's Child
	4. "I Want It That Way"        Backstreet Boys
	5. "Yellow Submarine"          The Beatles
	-->
	<software name="us_strt">
		<description>e-kara US 5-Songs Starter (US-M001)</description>
		<year>2000</year>
		<publisher>Takara</publisher>
		<part name="cart" interface="ekara_cart">
			<dataarea name="rom" size="0x080000">
				<rom name="us-m001.u1" size="0x080000" crc="8c12c0c2" sha1="8cc1b098894af25a4bfccada884125b66f5fe8b2"/>
			</dataarea>
		</part>
	</software>

	<!-- e-kara US Volume 1 (US-E001)
	1.  "Oops!...I Did It Again"       Britney Spears
	2.  "...Baby One More Time"        Britney Spears
	3.  "Bye Bye Bye"                  *N Sync
	4.  "It's Gonna Be Me"             *N Sync
	5.  "Take On Me"                   a1
	6.  "Aaron's Party (Come Get It)"  Aaron Carter
	7.  "If Only"                      Hanson
	8.  "He Loves U Not"               Dream
	9.  "The First Night"              Monica
	10. "I Need You"                   LeAnn Rimes
	-->
	<software name="us_vol1">
		<description>e-kara US Volume 1 (US-E001)</description>
		<year>2001</year> <!-- 2000 shown on screen, 2001 on cart -->
		<publisher>Takara</publisher>
		<part name="cart" interface="ekara_cart">
			<dataarea name="rom" size="0x100000">
				<rom name="us-e001.u1" size="0x100000" crc="29df4aea" sha1="b95835aaf8630b61b47e5da0968cd4a1dd3bc517"/>
			</dataarea>
		</part>
	</software>

	<!-- e-kara US Volume 2 (US-E002)
	1.  "Larger Than Life"          Backstreet Boys
	2.  "I'll Be There For You"     Backstreet Boys
	3.  "My Everything"             98 Degrees
	4.  "Dizzy"                     98 Degrees
	5.  "Independent Woman Part 1"  Destiny's Child
	6.  "Waiting For Tonight"       Jennifer Lopez
	7.  "Let Me Let Go"             Faith Hill
	8.  "There's Your Trouble"      Dixie Chicks
	9.  "5678"                      Steps
	10. "Stomp"                     Steps
	-->
	<software name="us_vol2">
		<description>e-kara US Volume 2 (US-E002)</description>
		<year>2001</year> <!-- 2000 shown on screen, 2001 on cart -->
		<publisher>Takara</publisher>
		<part name="cart" interface="ekara_cart">
			<dataarea name="rom" size="0x100000">
				<rom name="us-e002.u1" size="0x100000" crc="6c66772e" sha1="e1e719df1e51caaafd9b3af187059334f7abbba3"/>
			</dataarea>
		</part>
	</software>

	<!-- e-kara US Volume 3 (US-E003)
	1.  "Doesn't Really Matter (radio edit)"   Janet Jackson
	2.  "Saving All My Love For You"           Whitney Houston
	3.  "Water Runs Dry"                       Boys II Men
	4.  "I Want It That Way"                   Backstreet Boys
	5.  "Back To Your Heart"                   Backstreet Boys
	6.  "I Just Called To Say I Love You"      Stevie Wonder
	7.  "We're All Alone"                      Boz Scaggs
	8.  "Crazy For You"                        Madonna
	9.  "True Colors"                          Cyndi Lauper
	10. "Lovin' You"                           Minnie Riperton
	-->
	<software name="us_vol3">
		<description>e-kara US Volume 3 (US-E003)</description>
		<year>2001</year> <!-- 2000 shown on screen, 2001 on cart -->
		<publisher>Takara</publisher>
		<part name="cart" interface="ekara_cart">
			<dataarea name="rom" size="0x100000">
				<rom name="us-e003.u1" size="0x100000" crc="d90a7e58" sha1="37b899676935fb3dda266dc5614ef53cb2c33980"/>
			</dataarea>
		</part>
	</software>

	<!-- e-kara US Volume 4 (US-E004)
	1.  "Can't Buy Me Love"   The Beatles
	2.  "A Hard Day's Night"  The Beatles
	3.  "Ticket To Ride"      The Beatles
	4.  "Yesterday"           The Beatles
	5.  "Help"                The Beatles
	6.  "Michelle"            The Beatles
	7.  "Yellow Submarine"    The Beatles
	8.  "All My Loving"       The Beatles
	9.  "Drive My Car"        The Beatles
	10. "We Can Work It Out"  The Beatles
	-->
	<software name="us_vol4">
		<description>e-kara US Volume 4 (US-E004)</description>
		<year>2001</year> <!-- 2000 shown on screen, 2001 on cart -->
		<publisher>Takara</publisher>
		<part name="cart" interface="ekara_cart">
			<dataarea name="rom" size="0x100000">
				<rom name="us-e004.u1" size="0x100000" crc="790822e9" sha1="cc5806fdc79f777a42980d6825c92837b07fd80d"/>
			</dataarea>
		</part>
	</software>

	<!-- e-kara US Volume 5 (US-E005)
	1.  "Lucy In the Sky With Diamonds"  The Beatles
	2.  "All You Need Is Love"           The Beatles
	3.  "Hello Goodbye"                  The Beatles
	4.  "Hey Jude"                       The Beatles
	5.  "Ob-La-Di, Ob-La-Da"             The Beatles
	6.  "Get Back"                       The Beatles
	7.  "Come Together"                  The Beatles
	8.  "Oh! Darling"                    The Beatles
	9.  "Let It Be"                      The Beatles
	10. "The Long And Winding Road"      The Beatles
	-->
	<software name="us_vol5">
		<description>e-kara US Volume 5 (US-E005)</description>
		<year>2001</year> <!-- 2000 shown on screen, 2001 on cart -->
		<publisher>Takara</publisher>
		<part name="cart" interface="ekara_cart">
			<dataarea name="rom" size="0x100000">
				<rom name="us-e005.u1" size="0x100000" crc="edf1e4ce" sha1="7e5e3116f62897ae023c84842036f24b19c926cc"/>
			</dataarea>
		</part>
	</software>

	<!-- e-kara US Volume 6 (US-E006)
	1.  "Survivor (Album Version)"             Destiny's Child
	2.  "Jumpin', Jumpin'"                     Destiny's Child
	3.  "I Turn To You"                        Christina Aguilera
	4.  "As Long As You're Loving Me"          Vitamin C
	5.  "Body II Body"                         Samantha Mumba
	6.  "Love Don't Cost a Thing"              Jennifer Lopez
	7.  "Again"                                Janet Jackson
	8.  "If I Fall You're Going Down With Me"  Dixie Chicks
	9.  "Can't Fight The Moonlight"            LeAnn Rimes
	10. "American Pie (Album Version)"         Madonna
	-->
	<software name="us_vol6">
		<description>e-kara US Volume 6 (US-E006)</description>
		<year>2001</year> <!-- 2000 shown on screen, 2001 on cart -->
		<publisher>Takara</publisher>
		<part name="cart" interface="ekara_cart">
			<dataarea name="rom" size="0x100000">
				<rom name="us-e006.u1" size="0x100000" crc="e9aaca2f" sha1="983086f068ee38b970c01d2304e757148474aee3"/>
			</dataarea>
		</part>
	</software>

	<!-- e-kara US Volume 7 (US-E007)
	1.  "Show Me The Meaning of Being Lonely"  Backstreet Boys
	2.  "Lucky"                                Britney Spears
	3.  "When It's Over"                       Sugar Ray
	4.  "Bootylicious"                         Destiny's Child
	5.  "Nobody Wants to be Lonely"            Ricky Martin & Christina Aguilera
	6.  "Breathe"                              Faith Hill
	7.  "It's Gonna Be Me"                     *N Sync
	8.  "Don't Think I'm Not"                  Kandi
	9.  "Lady Marmalade"                       Christina Aguilera, Lik'Kim, Mya & Pink
	10. "God Bless The U.S.A."                 Lee Greenwood
	-->
	<software name="us_vol7">
		<description>e-kara US Volume 7 (US-E007)</description>
		<year>2002</year> <!-- 2002 shown on screen, 2001 on cart -->
		<publisher>Takara</publisher>
		<part name="cart" interface="ekara_cart">
			<dataarea name="rom" size="0x100000">
				<rom name="us-e007.u1" size="0x100000" crc="b7f5ca53" sha1="84af6d96512de96dbab03c236b3416b2e604f753"/>
			</dataarea>
		</part>
	</software>

	<!-- e-kara US Volume 8 'No Boys Allowed' (US-E008)
	1.  "I'm A Slave 4 U"           Britney Spears
	2.  "Stronger"                  Britney Spears
	3.  "Oops!...I Did It Again"    Britney Spears
	4.  "Breathe"                   Faith Hill
	5.  "Thank You"                 Dido
	6.  "He Loves U Not"            Dream
	7.  "Believe"                   Cher
	8.  "Case Of The Ex"            Mya
	9.  "Crush"                     Jennifer Paige
	10. "Back and Forth"            Aaliyah
	-->
	<software name="us_vol8">
		<description>e-kara US Volume 8 'No Boys Allowed' (US-E008)</description>
		<year>2002</year> <!-- 2002 shown on screen, 2001 on cart -->
		<publisher>Takara</publisher>
		<part name="cart" interface="ekara_cart">
			<dataarea name="rom" size="0x100000">
				<rom name="us-e008.u1" size="0x100000" crc="5cddaf1f" sha1="345ae679974ae5ae9b506b32323ada234c01f984"/>
			</dataarea>
		</part>
	</software>

	<!-- e-kara US Volume 9 'No Boys Allowed' (US-E009)
	1.  "So In Love With Two"        Mikaila
	2.  "Lady Marmalade"             Christina Aguilera, Lik'Kim, Mya & Pink
	3.  "Genie In A Bottle"          Christina Aguilera
	4.  "Bootylicious"               Destiny's Child
	5.  "Can't Fight The Moonlight"  LeAnn Rimes
	6.  "You Can't Hurry Love"       Dixie Chicks
	7.  "Hot Stuff"                  Donna Summer
	8.  "Crazy For You"              Madonna
	9.  "Someone To Call My Lover"   Janet Jackson
	10.  "All For You"               Janet Jackson
	-->
	<software name="us_vol9">
		<description>e-kara US Volume 9 'No Boys Allowed' (US-E009)</description>
		<year>2002</year> <!-- 2002 shown on screen, 2001 on cart -->
		<publisher>Takara</publisher>
		<part name="cart" interface="ekara_cart">
			<dataarea name="rom" size="0x100000">
				<rom name="us-e009.u1" size="0x100000" crc="0d9c402b" sha1="95652eb71dab74fbf05f8450f2a9b664b455deeb"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/gls.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="gls" description="VTech Genius Leader Select cartridges">

	<software name="srs">
		<description>Spielend Richtig Schreiben</description>
		<year>199?</year>
		<publisher>Video Technology</publisher>
		<info name="serial" value="80-2463" />

		<part name="rom" interface="genius_rom">
			<dataarea name="rom" size="0x40000">
				<rom name="27-05763-000.u2" size="0x40000" crc="5c6ada02" sha1="ee948b077a20fd3f4b4cdfcabeb09b17f9cc99c8"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/sv8000.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="sv8000" description="Bandai Super Vision 8000 cartridges">

	<!-- 1 - MISSILEVADER -->
	<software name="misvader">
		<description>Missilevader</description>
		<year>1979</year>
		<publisher>Bandai</publisher>
		<info name="alt_title" value="ミサイルベーダー" />
		<part name="cart" interface="sv8000_cart">
			<dataarea name="rom" size="0x1000">
				<rom name="missilevader.bin" size="0x1000" crc="a634a472" sha1="ac4d4a6adae0c7bf19b3c70e70d6541e0814ab34" />
			</dataarea>
		</part>
	</software>

	<!-- 2 - SPACEFIRE -->
	<software name="spfire">
		<description>Space Fire</description>
		<year>1980</year>
		<publisher>Bandai</publisher>
		<info name="alt_title" value="スペースファイヤー" />
		<part name="cart" interface="sv8000_cart">
			<dataarea name="rom" size="0x1000">
				<rom name="spacefire.bin" size="0x1000" crc="85ce4a88" sha1="3bd00bd4978bc1d27a8e31da00f3f24bcb4f76fd" />
			</dataarea>
		</part>
	</software>

	<!-- 3 - OTHELLO -->
	<software name="othello">
		<description>Othello</description>
		<year>1980</year>
		<publisher>Bandai</publisher>
		<info name="alt_title" value="オセロ" />
		<part name="cart" interface="sv8000_cart">
			<dataarea name="rom" size="0x1000">
				<rom name="othello.bin" size="0x1000" crc="fb3c070e" sha1="9df64c78d32f5d31caea936877f47f8d1cdf538b" />
			</dataarea>
		</part>
	</software>

	<!-- 4 - GUNPROFESSIONAL -->
	<software name="gunprof">
		<description>Gun Fighter</description>
		<year>1980</year>
		<publisher>Bandai</publisher>
		<info name="alt_title" value="ガンプロフェッショナル" />
		<part name="cart" interface="sv8000_cart">
			<dataarea name="rom" size="0x1000">
				<rom name="gunprofessional.bin" size="0x1000" crc="05db65c0" sha1="09dd817ba35103507d50d44583ddcbb74e463dc8" />
			</dataarea>
		</part>
	</software>

	<!-- 5 - PACPACBIRD -->
	<software name="pacpac">
		<description>Pac Pac Bird</description>
		<year>1980</year>
		<publisher>Bandai</publisher>
		<info name="alt_title" value="パクパクバード" />
		<part name="cart" interface="sv8000_cart">
			<dataarea name="rom" size="0x1000">
				<rom name="pacpacbird.bin" size="0x1000" crc="b550e119" sha1="57923a51f8d52f341fe4bec0401189058875fc69" />
			</dataarea>
		</part>
	</software>

	<!-- 6 - SUBMARINE -->
	<software name="submar">
		<description>Submarine</description>
		<year>1980</year>
		<publisher>Bandai</publisher>
		<info name="alt_title" value="サブマリン" />
		<part name="cart" interface="sv8000_cart">
			<dataarea name="rom" size="0x1000">
				<rom name="submarine.bin" size="0x1000" crc="b7d67a05" sha1="1f4929c019608342363bc6337650cc8e763c4430" />
			</dataarea>
		</part>
	</software>

	<!-- 7 - BEAMGALAXIAN -->
	<software name="beamgala">
		<description>Beamgalaxian</description>
		<year>1980</year>
		<publisher>Bandai</publisher>
		<info name="alt_title" value="ビームギャラクシアン" />
		<part name="cart" interface="sv8000_cart">
			<dataarea name="rom" size="0x1000">
				<rom name="beamgalaxian.bin" size="0x1000" crc="009f9567" sha1="78b0d57e83f0a428befac57d5c0869eeefc35953" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/special_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="special_flop" description="Specialist MX disk images">

	<software name="bstcpm0">
		<description>BST_CPM0</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="disk" interface="floppy_5_25">
			<dataarea name="flop" size="819200">
				<rom name="bst_cpm0.odi" size="819200" crc="0bc1a7e8" sha1="d6af8ef893a7e099d7d468a1a53bb107dbe5ce0d"/>
			</dataarea>
		</part>
	</software>

	<software name="bstmx0">
		<description>bst_mx0</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="disk" interface="floppy_5_25">
			<dataarea name="flop" size="819200">
				<rom name="bst_mx0.odi" size="819200" crc="15bffc00" sha1="320871829e8cbe8f9230edad191f2047b9c9ddfc"/>
			</dataarea>
		</part>
	</software>


</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/clipper_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="clipper_flop" description="PDC Clipper disks">
	<software name="system" supported="no">
		<description>System</description>
		<year>1984</year>
		<publisher>Professional Data Computer</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="174848">
				<rom name="1.d64" size="174848" crc="0d179f77" sha1="3c40739a392efd2758f4ad9f8239cd38b4d69172"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="174848">
				<rom name="2.d64" size="174848" crc="3fe1ff92" sha1="fd80ea019c307e4a5f8dff1d4fce0d00017796cd"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<dataarea name="flop" size="174848">
				<rom name="3.d64" size="174848" crc="530ad6ef" sha1="14d97c707438ddd4471d997202883d787b3926ea"/>
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_5_25">
			<dataarea name="flop" size="174848">
				<rom name="4.d64" size="174848" crc="176883d9" sha1="94a473032073dc7e973a9c79aacc30ff4a812fcf"/>
			</dataarea>
		</part>
	</software>
</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/gjrstar.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="gjrstar" description="VTech Genius Junior Redstar cartridges">

	<!-- According to the boxart, this is compatible with: Junior Redstar/Redstar 2/Redstar 3 -->
	<software name="wortspie">
		<description>Wortspiele</description>
		<year>200?</year>
		<publisher>Video Technology</publisher>
		<info name="serial" value="80-10171" />
		<part name="rom" interface="genius_rom">
			<dataarea name="rom" size="0x40000">
				<rom name="27-5883-00" size="0x40000" crc="99214bce" sha1="75294fbc411b0b39b3db4727824faf29127675af"/>
			</dataarea>
		</part>
	</software>

	<!-- Russian carts for Precomputer Elektronik (Прекомпьютер Электроник), compatibility with clones from other regions is unknown -->

	<software name="matematika">
		<description>Matematika - Podarok Pervoklassniku</description> <!-- Mathematics - Gift for a First Grader -->
		<year>????</year>
		<publisher>Video Technology / DzhiNo</publisher> <!-- VTech / ДжиНо -->
		<info name="serial" value="80-10126-04" /> <!-- № 4 -->
		<info name="alt_title" value="Математика - Подарок Первокласснику"/>
		<part name="rom" interface="genius_rom">
			<dataarea name="rom" size="0x10000">
				<rom name="80-10126-04.bin" size="0x10000" crc="5c0c2e30" sha1="b75119188354833695c1e9a7686ac244b474ff09"/> <!-- 27C512 inside the cart, second half empty -->
			</dataarea>
		</part>
	</software>

	<software name="nazagadki">
		<description>Narodnyye Zagadki</description> <!-- Folk Riddles -->
		<year>????</year>
		<publisher>Video Technology / DzhiNo</publisher> <!-- VTech / ДжиНо -->
		<info name="serial" value="80-10126-08" /> <!-- № 8 -->
		<info name="alt_title" value="Народные Загадки"/>
		<part name="rom" interface="genius_rom">
			<dataarea name="rom" size="0x10000">
				<rom name="80-10126-08.bin" size="0x10000" crc="1c667c44" sha1="32f7a33a6ae95dc9b68e215e73a8c4a203d39033"/> <!-- 27C512 inside the cart, second half empty -->
			</dataarea>
		</part>
	</software>

	<software name="poiskakhds">
		<description>V Poiskakh Dukhovnykh Sokrovishch</description> <!-- In Search of Spiritual Treasures -->
		<year>????</year>
		<publisher>Video Technology / DzhiNo</publisher> <!-- VTech / ДжиНо -->
		<info name="serial" value="80-10126-14" /> <!-- № 14 -->
		<info name="alt_title" value="В Поисках Духовных Сокровищ"/>
		<part name="rom" interface="genius_rom">
			<dataarea name="rom" size="0x10000">
				<rom name="80-10126-14.bin" size="0x10000" crc="87e0ba37" sha1="902d1417d1fcc26216b35d18c685bbcf5b65b96c"/> <!-- 27C512 inside the cart -->
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/pasopia_cass.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="pasopia_cass" description="Toshiba Personal Computer Pasopia PA7010 cassettes">

<!--
    Undumped

    T-1054 - オカルト ハウス
 -->

	<software name="gameshuu">
		<description>Pasopia Game-shuu</description>
		<year>1982</year>
		<publisher>Toshiba</publisher>
		<info name="serial" value="PA6002"/>
		<info name="alt_title" value="パソピア ゲーム集"/>
		<part name="cass1" interface="pasopia_cass">
			<dataarea name="cass" size="68596062">
				<rom name="pa6002.wav" size="68596062" crc="f8a3ea13" sha1="01436203bb2e7a1b7f3adec812f6d2edebcb2cc7"/>
			</dataarea>
		</part>
	</software>

	<software name="smpleprg">
		<description>Sample Program PA7010-you</description>
		<year>1982</year>
		<publisher>Toshiba</publisher>
		<info name="serial" value="PZA-383"/>
		<info name="alt_title" value="SAMPLE PROGRAM PA7010用"/>
		<part name="cass1" interface="pasopia_cass">
			<dataarea name="cass" size="22310064">
				<rom name="pza-383.wav" size="22310064" crc="98069673" sha1="7500579c6b43736fdcb17d6929af8a7077ca72e8"/>
			</dataarea>
		</part>
	</software>

	<software name="parttime">
		<description>Part-Timer no Kyuuyo Keisan</description>
		<year>1982</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="T-3010"/>
		<info name="alt_title" value="パートタイマーの給与計算"/>
		<part name="cass1" interface="pasopia_cass">
			<dataarea name="cass" size="14950165">
				<rom name="t-3010.wav" size="14950165" crc="d7c6745d" sha1="fc0ae43e62128e02000bf534c156ac1c0eebb63b"/>
			</dataarea>
		</part>
	</software>

	<software name="derby">
		<description>Pasopia Derby</description>
		<year>1982</year>
		<publisher>Hudson</publisher>
		<info name="serial" value="T-1030"/>
		<info name="alt_title" value="パソピア ダービー"/>
		<part name="cass1" interface="pasopia_cass">
			<dataarea name="cass" size="13059875">
				<rom name="t-1030.wav" size="13059875" crc="0c2702f7" sha1="544e120e0dc5d226072371841e5e1982f015353b"/>
			</dataarea>
		</part>
	</software>

	<software name="golf">
		<description>The Golf</description>
		<year>1982</year>
		<publisher>Micro Cabin</publisher>
		<info name="serial" value="T-201"/>
		<info name="alt_title" value="ザ・ゴルフ"/>
		<part name="cass1" interface="pasopia_cass">
			<dataarea name="cass" size="19156507">
				<rom name="t-201.wav" size="19156507" crc="916e814e" sha1="2e2c61129cc2359b35e1aa9d88130326b7b5ca66"/>
			</dataarea>
		</part>
	</software>

	<software name="hilight">
		<description>Pasopia Game Highlight</description>
		<year>1982</year>
		<publisher>Toshiba</publisher>
		<info name="serial" value="PZA-410"/>
		<info name="alt_title" value="パソピアゲームハイライト"/>
		<part name="cass1" interface="pasopia_cass">
			<feature name="part_id" value="A - T-BASIC用"/>
			<dataarea name="cass" size="80066535">
				<rom name="pza-410.wav" size="80066535" crc="5849a0f8" sha1="7c64bb429033b0f39a703524546bc96ae706d3cf"/>
			</dataarea>
		</part>
		<part name="cass2" interface="pasopia_cass">
			<feature name="part_id" value="B - OA-BASIC用"/>
			<dataarea name="cass" size="80066535">
				<rom name="pasopia game highlight oa-basic.wav" size="80066535" status="nodump"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/stepone_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="stepone_flop" description="Ericsson PC step/one diskettes">

	<!-- OS -->
	<!-- https://youtu.be/BMvwbZyB3bQ -->
	<software name="dos125">
		<description>MS-DOS v1.25</description>
		<year>1982</year>
		<publisher>Microsoft</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="167674">
				<rom name="BASIC.IMD" size="167674" crc="6789a422" sha1="2db2140562f1e033719dd68befd27ef34e6ef539" offset="0" />
			</dataarea>
		</part>
	</software>

	<!-- Apps -->
	<software name="combi" supported="no">
		<description>Custom integrated office suite</description>
		<year>1983</year>
		<publisher>OMS - Office Management Systems AB</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="526850">
				<rom name="CMBSTBM.IMD" size="526850" crc="9a93f2e4" sha1="2b4b6cbce1534a67ba4eca275ef018637261c3ed" offset="0" />
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="282664">
				<rom name="CMBSTPE1.IMD" size="282664" crc="8a71d87f" sha1="b442573aed547fb7748c60d055405e2e92995fd8" offset="0" />
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<dataarea name="flop" size="316889">
				<rom name="CMBSTPE2.IMD" size="316889" crc="c839115b" sha1="d8054d3e7d3516a7cdee33b02c0ae79ae0279caf" offset="0" />
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_5_25">
			<dataarea name="flop" size="527874">
				<rom name="CMBSTPO1.IMD" size="527874" crc="80eb83d0" sha1="b81bfa66ae477afd087b8d54c21fe98c778e032f" offset="0" />
			</dataarea>
		</part>
		<part name="flop5" interface="floppy_5_25">
			<dataarea name="flop" size="683218">
				<rom name="CMBSTPO2.IMD" size="683218" crc="5357135d" sha1="cce5e51be38180003b926704d79990021e918bd0" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="multip14">
		<description>Microsoft Multiplan v1.04</description>
		<year>1982</year>
		<publisher>Microsoft</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="118615">
				<rom name="MULTIPL.IMD" size="118615" crc="756368a3" sha1="9bbd27d5ac37ac2ef40f68a21a4a9cd93c1c5648" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="pasc311">
		<description>Microsoft Pascal v3.11</description>
		<year>1983</year>
		<publisher>Ericsson/Microsoft</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="705796">
				<rom name="PASCAL1.IMD" size="705796" crc="c4fb00a0" sha1="8b3a6e40b7d198aef6ec04eeff8c634c137d9cc5" offset="0" />
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="596955">
				<rom name="PASCAL2.IMD" size="596955" crc="1091c2f4" sha1="b54569167d1263632535244d1b4aff811c2f4c91" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="rjev10m">
		<description>RJE - IBM 3780 Remote Batch Terminal Emulator v1.0M</description>
		<year>1982</year>
		<publisher>InterCom Inc/Matsushita</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="36358">
				<rom name="RJE3780.IMD" size="36358" crc="22365c54" sha1="3e4c30701eb36809b08eefbec5c808aa1d758795" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="wstar324">
		<description>Wordstar v3.24</description>
		<year>1982</year>
		<publisher>MicroPro International Corporation</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="103798">
				<rom name="WORDSTAR.IMD" size="103798" crc="a9b57ef8" sha1="8253ec46818b0855d8bab860d6afd2ddfc0996a4" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spel">
		<description>Collections of small games</description>
		<year>1987</year>
		<publisher>Various authors</publisher>
		<part name="spel1" interface="floppy_5_25">
			<dataarea name="flop" size="666392">
				<rom name="SPEL1.IMD" size="666392" crc="62eae5c0" sha1="e33e9e901a649114312c75780fefbd9bb27a18c7" offset="0" />
			</dataarea>
		</part>
		<part name="spel2" interface="floppy_5_25">
			<dataarea name="flop" size="509004">
				<rom name="SPEL2.IMD" size="509004" crc="07abdac4" sha1="a665d8862f80234ca85a9dc14ae89ff202c70860" offset="0" />
			</dataarea>
		</part>
		<part name="spel3" interface="floppy_5_25">
			<dataarea name="flop" size="461481">
				<rom name="SPEL3.IMD" size="461481" crc="771eafc3" sha1="1bc8879355dee5877ea8bb1c16256fa28eb10547" offset="0" />
			</dataarea>
		</part>
	</software>
</softwarelist>
