=== monster-penguin/retrobios/bios/Arcade/MAME/hash/softwarelist.dtd
<!ELEMENT softwarelist (notes?, software+)>
	<!ATTLIST softwarelist name CDATA #REQUIRED>
	<!ATTLIST softwarelist description CDATA #IMPLIED>
	<!ELEMENT notes (#PCDATA)>
	<!ELEMENT software (description, year, publisher, notes?, info*, sharedfeat*, part*)>
		<!ATTLIST software name CDATA #REQUIRED>
		<!ATTLIST software cloneof CDATA #IMPLIED>
		<!ATTLIST software supported (yes|partial|no) "yes">
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT publisher (#PCDATA)>
		<!ELEMENT info EMPTY>
			<!ATTLIST info name CDATA #REQUIRED>
			<!ATTLIST info value CDATA #IMPLIED>
		<!ELEMENT sharedfeat EMPTY>
			<!ATTLIST sharedfeat name CDATA #REQUIRED>
			<!ATTLIST sharedfeat value CDATA #IMPLIED>
		<!ELEMENT part (feature*, dataarea*, diskarea*, dipswitch*)>
			<!ATTLIST part name CDATA #REQUIRED>
			<!ATTLIST part interface CDATA #REQUIRED>
			<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
			<!ELEMENT feature EMPTY>
				<!ATTLIST feature name CDATA #REQUIRED>
				<!ATTLIST feature value CDATA #IMPLIED>
			<!ELEMENT dataarea (rom*)>
				<!ATTLIST dataarea name CDATA #REQUIRED>
				<!ATTLIST dataarea size CDATA #REQUIRED>
				<!ATTLIST dataarea width (8|16|32|64) "8">
				<!ATTLIST dataarea endianness (big|little) "little">
				<!ELEMENT rom EMPTY>
					<!ATTLIST rom name CDATA #IMPLIED>
					<!ATTLIST rom size CDATA #IMPLIED>
					<!ATTLIST rom crc CDATA #IMPLIED>
					<!ATTLIST rom sha1 CDATA #IMPLIED>
					<!ATTLIST rom offset CDATA #IMPLIED>
					<!ATTLIST rom value CDATA #IMPLIED>
					<!ATTLIST rom status (baddump|nodump|good) "good">
					<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue|reload_plain|ignore) #IMPLIED>
			<!ELEMENT diskarea (disk*)>
				<!ATTLIST diskarea name CDATA #REQUIRED>
				<!ELEMENT disk EMPTY>
					<!ATTLIST disk name CDATA #REQUIRED>
					<!ATTLIST disk sha1 CDATA #IMPLIED>
					<!ATTLIST disk status (baddump|nodump|good) "good">
					<!ATTLIST disk writeable (yes|no) "no">
			<!ELEMENT dipswitch (dipvalue*)>
				<!ATTLIST dipswitch name CDATA #REQUIRED>
				<!ATTLIST dipswitch tag CDATA #REQUIRED>
				<!ATTLIST dipswitch mask CDATA #REQUIRED>
				<!ELEMENT dipvalue EMPTY>
					<!ATTLIST dipvalue name CDATA #REQUIRED>
					<!ATTLIST dipvalue value CDATA #REQUIRED>
					<!ATTLIST dipvalue default (yes|no) "no">

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/trsm100.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0

Option ROM booting instructions:

1. Start BASIC
2. Type CALL 63012 (regular titles) or CALL 63013,1 (Traveling Software titles)
-->
<softwarelist name="trsm100" description="TRS-80 Model 100 Option ROMs">
	<software name="r2c">
		<description>ROM2/Cleuseau</description>
		<year>198?</year>
		<publisher>Polar Engineering</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x8000">
				<rom name="r2c100.bin" size="0x8000" crc="3adacaa6" sha1="6ddf43047a819eb88367ebe6ace1a0166e6dbb03" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="tsrandom">
		<description>TS-RANDOM v1.3</description>
		<year>1986</year>
		<publisher>Traveling Software</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x8000">
				<rom name="rand100.bin" size="0x8000" crc="87781c9c" sha1="7749c1ecbf877151eba2e25f154b06c57324b25c" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="tword">
		<description>T-Word with Sardine v1.34</description>
		<year>1986</year>
		<publisher>Traveling Software</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x8000">
				<rom name="sard100.bin" size="0x8000" crc="ad08d509" sha1="4488cf7f90f1a121ee68ce1db10d45a75c112934" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="multipln">
		<description>Microsoft Multiplan v1.00</description>
		<year>1983</year>
		<publisher>Tandy/Radio Shack</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x8000">
				<rom name="multipln.bin" size="0x8000" crc="58e7052d" sha1="02298ab5e319b352dd60f281632b0a8d18f5c916" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="is">
		<description>Interactive Solutions</description>
		<year>1984</year>
		<publisher>Tandy/Radio Shack</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x8000">
				<rom name="is100.bin" size="0x8000" crc="b8e734ec" sha1="338ffe692f29c2e846bbc4343bc958ed3f9d3bc2" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="tsdos">
		<description>TS-DOS v4.00</description>
		<year>1987</year>
		<publisher>Traveling Software</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x8000">
				<rom name="tsdos100.bin" size="0x8000" crc="b359d304" sha1="2b8105b8a46c3f6a90f46f567fffea18fa974c63" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="ur2">
		<description>The Ultimate ROM II v2.12</description>
		<year>1986</year>
		<publisher>Traveling Software</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x8000">
				<rom name="ur2100.bin" size="0x8000" crc="2e3ebe41" sha1="b685f58cf3befa3f2ca5d076c4fa90aa348e634a" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="cardfile">
		<description>Card File Program</description>
		<year>1989</year>
		<publisher>Tony B. Anderson</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x8000">
				<rom name="crdfil.bin" size="0x8000" crc="b77a6ec5" sha1="a42291bda195fe567faa6200ba6083771902702b" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="logit">
		<description>Log-It 100 v1.1</description>
		<year>1985</year>
		<publisher>Abby Levine / Barry Minnerly</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x8000">
				<rom name="logit100.bin" size="0x2000" crc="49561afe" sha1="6a21091fd4ed258d65dce13616d8e961abb1f4b4" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="ramplus">
		<description>RAM+ v2.5</description>
		<year>1985</year>
		<publisher>PCSG</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x8000">
				<rom name="ramplus.bin" size="0x2000" crc="1369956a" sha1="d8e55a232ae141a9e56aa9a27b166f10f342fead" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="bp" supported="no">
		<description>Booster Pack</description>
		<year>198?</year>
		<publisher>Traveling Software</publisher>

		<part name="cart" interface="trsm100_cart">
			<dataarea name="rom" size="0x30000">
				<rom name="bp1.bin" size="0x8000" crc="2a4ea4c8" sha1="fa46c038d6bca5f1f3cf6fac89a4e60dcbb5d3ff" offset="0x00000" />
				<rom name="bp2.bin" size="0x8000" crc="2293043b" sha1="79d2609e9b2bc2e88cccc55a2c57e523b3b66197" offset="0x08000" />
				<rom name="sard1bp.bin" size="0x8000" crc="1e545076" sha1="0e6bb627464ca2fb503dbb5fc31bea81d7cd1cd0" offset="0x10000" />
				<rom name="sard2bp.bin" size="0x8000" crc="4d53a912" sha1="2db1bb726e085ab8b804cbef0ba21615cc12a48b" offset="0x18000" />
				<rom name="sard3bp.bin" size="0x8000" crc="03ec495d" sha1="ee0904599fbcf45b6138f9f28f45ae27a6a67ba2" offset="0x20000" />
				<rom name="sard4bp.bin" size="0x8000" crc="4a06dbf8" sha1="52207043ed236c2c6a378083ddaeabab668db3d5" offset="0x28000" />
			</dataarea>
		</part>
	</software>
</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/tandy6k.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="tandy6k" description="Tandy 6000 disk images">

	<software name="xenix32">
		<description>Tandy Xenix 3.2</description>
		<year>1987</year>
		<publisher>Tandy Radio Shack</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="618693">
				<rom name="xenix1.imd" size="618693" crc="0b28867d" sha1="275e642d0f1396012051a1a40d4c1f6b7932f049"/>
			</dataarea>
		</part>

		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="598600">
				<rom name="xenix2.imd" size="598600" crc="3befd970" sha1="d6b13a10b8b08bd783d45f6250c3369e30781ec5"/>
			</dataarea>
		</part>

		<part name="flop3" interface="floppy_5_25">
			<dataarea name="flop" size="622494">
				<rom name="xenix3.imd" size="622494" crc="1935aa13" sha1="5b7dc78b509a3ccadcfc64c4e7521bc03a9c7ea0"/>
			</dataarea>
		</part>

		<part name="flop4" interface="floppy_5_25">
			<dataarea name="flop" size="619428">
				<rom name="xenix4.imd" size="619428" crc="d716b5b3" sha1="96d54e3efc2831682995f0638da2634b373fc194"/>
			</dataarea>
		</part>

		<part name="flop5" interface="floppy_5_25">
			<dataarea name="flop" size="1255478">
				<rom name="xenix5.imd" size="1255478" crc="18a55fe6" sha1="38ac84cb2ea47140210335dc706c3a04c5df627c"/>
			</dataarea>
		</part>
	</software>

	<software name="xenix30d">
		<description>Tandy Xenix 3.0 Development System</description>
		<year>1985</year>
		<publisher>Tandy Radio Shack</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="622499">
				<rom name="devsys01of14.imd" size="622499" crc="44c85394" sha1="81a3a7c395595edd9c743572b4736362aa1695b8"/>
			</dataarea>
		</part>

		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="618926">
				<rom name="devsys02of14.imd" size="618926" crc="de5e97f7" sha1="6282a9248a0b7685204530ff70e8832aeaa5e295"/>
			</dataarea>
		</part>

		<part name="flop3" interface="floppy_5_25">
			<dataarea name="flop" size="620970">
				<rom name="devsys03of14.imd" size="620970" crc="8771520a" sha1="9b83da4609562e8b1e4e88f688b00f7771766326"/>
			</dataarea>
		</part>

		<part name="flop4" interface="floppy_5_25">
			<dataarea name="flop" size="409927">
				<rom name="devsys04of14.imd" size="409927" crc="b9d71b10" sha1="0c577fae74fb79a3943fe2d37c52358a9694a177"/>
			</dataarea>
		</part>

		<part name="flop5" interface="floppy_5_25">
			<dataarea name="flop" size="573447">
				<rom name="devsys05of14.imd" size="573447" crc="5cf99c5c" sha1="d5bcfedc1f5180f0c2a3613f3ba9d5cd3b06c5d4"/>
			</dataarea>
		</part>

		<part name="flop6" interface="floppy_5_25">
			<dataarea name="flop" size="496797">
				<rom name="devsys06of14.imd" size="496797" crc="caa562d5" sha1="955d4ccd4475fbf38653f5082f8f59f8da1df0be"/>
			</dataarea>
		</part>

		<part name="flop7" interface="floppy_5_25">
			<dataarea name="flop" size="614323">
				<rom name="devsys07of14.imd" size="614323" crc="b79dddf9" sha1="e8847de6e87c239a8976395411643a9b77ac0b88"/>
			</dataarea>
		</part>

		<part name="flop8" interface="floppy_5_25">
			<dataarea name="flop" size="605129">
				<rom name="devsys08of14.imd" size="605129" crc="1ebb5305" sha1="7d778c33539f34e8d3fb6828178f46c08cf3dbc2"/>
			</dataarea>
		</part>

		<part name="flop9" interface="floppy_5_25">
			<dataarea name="flop" size="623014">
				<rom name="devsys09of14.imd" size="623014" crc="27e502e1" sha1="61afc2c4bb45d4ca712dc8b6a9f8844225f25717"/>
			</dataarea>
		</part>

		<part name="flop10" interface="floppy_5_25">
			<dataarea name="flop" size="603597">
				<rom name="devsys10of14.imd" size="603597" crc="a94c89fd" sha1="39152da3c8f6bd32efe6c65cb6893a6df0ae68a5"/>
			</dataarea>
		</part>

		<part name="flop11" interface="floppy_5_25">
			<dataarea name="flop" size="619949">
				<rom name="devsys11of14.imd" size="619949" crc="b3e0d3d3" sha1="8717fbf90451d82ffc3a5b51a9321c2f9abd0025"/>
			</dataarea>
		</part>

		<part name="flop12" interface="floppy_5_25">
			<dataarea name="flop" size="623526">
				<rom name="devsys12of14.imd" size="623526" crc="0fc79c44" sha1="033417932b711490c0399a984b2bd9e80d788599"/>
			</dataarea>
		</part>

		<part name="flop13" interface="floppy_5_25">
			<dataarea name="flop" size="624548">
				<rom name="devsys13of14.imd" size="624548" crc="6a0e1790" sha1="dd12a00e9db8c1581d8404c75f26cd3d1236a8c7"/>
			</dataarea>
		</part>

		<part name="flop14" interface="floppy_5_25">
			<dataarea name="flop" size="623526">
				<rom name="devsys14of14.imd" size="623526" crc="24d1cab5" sha1="f4769719ac2dd2d67f556238b74a4e0c99569a60"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/ramstar.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0

It is unknown if more cartridges were sold (probably yes).

Entries are sorted by description.
-->

<softwarelist name="ramstar" description="Ram Star multi-game cartridges">
	<software name="amdream" supported="no">
		<description>American Dream</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="84022997" sha1="f736db5a66193a36b1aaa8cbdca5e4a3521c2e86"/>
			</dataarea>
		</part>
	</software>

	<software name="barfever" supported="no">
		<description>Bar Fever (set 1)</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="cb4d8ab0" sha1="b61fea3fe206538d8539d66306ef4e3d531c6767"/>
			</dataarea>
		</part>
	</software>

	<software name="barfevera" cloneof="barfever" supported="no"> <!-- TODO: verify parent / clone relationship -->
		<description>Bar Fever (set 2)</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="6cce1582" sha1="35c31cc577e7efc95ca67c058e67e8c5b3e8a7ba"/>
			</dataarea>
		</part>
	</software>

	<software name="bearctry" supported="no">
		<description>Bear Country</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="959f14f0" sha1="05d3c5a7cf156efdada5ae48c8734fa753cdbe54"/>
			</dataarea>
		</part>
	</software>

	<software name="gamerica" supported="no">
		<description>Great America</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="0daea153" sha1="73b7cf77e7441135a95de00ca306c34fcfa160aa"/>
			</dataarea>
		</part>
	</software>

	<software name="irishl" supported="no">
		<description>Irish Luck</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="1cabece9" sha1="f254f5603341e9b32075996c14900c8a4706886c"/>
			</dataarea>
		</part>
	</software>

	<software name="jokerpkr" supported="no">
		<description>Joker Poker</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="5672dd49" sha1="2c7c3838518035bb66c28e843c3c97ff2864d09c"/>
			</dataarea>
		</part>
	</software>

	<software name="luckyc" supported="no">
		<description>Lucky Critters</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="e7459b31" sha1="7dc375d2ebaacc737a87965860aa4903601cdc93"/>
			</dataarea>
		</part>
	</software>

	<software name="lucky7" supported="no">
		<description>Lucky Seven</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="ef43619d" sha1="b630c05e9bb45d3bd3d38a449ecca99eb3e754f9"/>
			</dataarea>
		</part>
	</software>

	<software name="lucky7s" supported="no"> <!-- TODO: maybe related to the above entry? -->
		<description>Lucky Sevens</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="73517705" sha1="f64ee18f90795de99dfc25fc568b1928c791209d"/>
			</dataarea>
		</part>
	</software>

	<software name="nevadacl" supported="no">
		<description>Nevada Club</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="05784e10" sha1="fe851223fc73f11486468452d3dd7cb5b1c68255"/>
			</dataarea>
		</part>
	</software>

	<software name="rainbowm" supported="no">
		<description>Rainbow Magic</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="095f157d" sha1="757c322532c323a3c12495fb699489e28e7ad798"/>
			</dataarea>
		</part>
	</software>

	<software name="silversl" supported="no">
		<description>Silver Slots</description>
		<year>1991?</year>
		<publisher>Ram Star</publisher>
		<part name="rom" interface="ramstar">
			<feature name="u1" value="27C512"/>
			<feature name="u2" value="X24C04"/>
			<dataarea name="rom" size="0x10000">
				<rom name="27c512.u1" size="0x10000" crc="b4c4f38b" sha1="df27c86e19881e8616638828edb529f6aa4dcec2"/>
			</dataarea>
		</part>
	</software>
</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/pet_quik.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="pet_quik" description="Commodore PET quickload">

	<!-- https://www.youtube.com/watch?v=OBEfKMFq8lo -->
	<software name="npa">
		<description>No Pets Allowed</description>
		<year>2010</year>
		<publisher>Orb</publisher>
		<!-- cbm4032 only -->

		<part name="quik" interface="cbm_quik">
			<dataarea name="quik" size="31382">
				<rom name="npa.prg" size="31382" crc="55295e40" sha1="43fb301f7f22878773ef9692ea7763191c085244"/>
			</dataarea>
		</part>
	</software>

	<!-- https://www.youtube.com/watch?v=gYHYplCyrM0 -->
	<software name="hardcore">
		<description>Hardcore Petting</description>
		<year>2010</year>
		<publisher>Noice</publisher>
		<!-- 8K RAM -->

		<part name="quik" interface="cbm_quik">
			<dataarea name="quik" size="6013">
				<rom name="hardcore_petting.prg" size="6013" crc="4f2853cf" sha1="c1e4f0d959c69c08c7ea4ea428736bc3ea0a2176"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/jb3000_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="jb3000_flop" description="Panasonic JB-3000 diskettes">

	<!-- OS 8" -->
	<software name="dos125"> <!-- From https://archive.org/details/JB-3000-MS-DOS -->
		<description>MS-DOS v1.25</description>
		<year>1982</year>
		<publisher>Microsoft</publisher>

		<part name="flop1" interface="floppy_8">
			<dataarea name="flop" size="200914">
				<rom name="JB-3000 MS-DOS (8-inch).imd" size="200914" crc="8aba9f35" sha1="7dba4f64296039d88c35098c71f30ab32e9e081e" offset="0" />
			</dataarea>
		</part>
	</software>

	<!-- Apps -->

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/to770a_cart.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0

Thanks to DCMOTO (http://dcmoto.free.fr) for info!

The Arabic BASIC 128 cartridge is useful only on an Arabic TO7/70!
-->
<softwarelist name="to770a_cart" description="Thomson TO7/70 Arabic cartridges">

	<software name="basic128">
		<description>BASIC 128 (Arab, v1.0)</description>
		<year>1985</year>
		<publisher>Thomson / Microsoft</publisher>
		<info name="alt_title" value="BASIC 128 Microsoft 1.0" />

		<part name="cart" interface="to_cart">
			<dataarea name="rom" size="65536">
				<rom name="basic128.bin" size="65536" crc="ba082b73" sha1="bdcb3b2b0b4f0e56bda55dfeee220da9473143e2" offset="0" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== monster-penguin/retrobios/bios/Arcade/MAME/hash/bbc_flop_6502.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0

Acorn BBC Micro - 6502 2nd Processor Discs

    Loading Instructions:

      Hold down the SHIFT key and press and release the BREAK key.
-->

<softwarelist name="bbc_flop_6502" description="Acorn 6502 2nd Processor discs">

	<software name="6502dev">
		<description>6502 Development Package</description>
		<year>1985</year>
		<publisher>Acornsoft</publisher>
		<info name="release" value="SNL05" />
		<info name="usage" value="Requires 6502 2nd Processor" />
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="53760">
				<rom name="6502development.ssd" size="53760" crc="219eefd1" sha1="d408d6d14d442c9e77be78fecef4b223e0c2404f"/>
			</dataarea>
		</part>
	</software>

	<software name="advbasic">
		<description>Advanced BASIC</description>
		<year>1987</year>
		<publisher>Tubelink</publisher>
		<info name="usage" value="Requires 6502 2nd Processor" />
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="87040">
				<rom name="Advanced BASIC 1.02.ssd" size="87040" crc="f54bd1dd" sha1="3ffb605dfa7e07f37d70364e06487b95a5ec427c"/>
			</dataarea>
		</part>
	</software>

	<software name="bitstik1">
		<description>Bitstik Graphics System</description>
		<year>1984</year>
		<publisher>Acorn</publisher>
		<info name="release" value="ANF04" />
		<info name="usage" value="Requires 6502 2nd Processor" />
		<part name="flop1" interface="floppy_5_25">
			<feature name="part_id" value="System Master Disc"/>
			<dataarea name="flop" size="204800">
				<rom name="bitstik1.0_system_master.ssd" size="204800" crc="77996ac8" sha1="0de49dc2535dfe27915a58dfc71729ecd14f7515"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<feature name="part_id" value="Buffer Disc"/>
			<dataarea name="flop" size="204800">
				<rom name="bitstik1.0_buffer.ssd" size="204800" crc="2a58f413" sha1="2ab1f5da153d40517a9e68bcaf3e579b373d2dc6"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<feature name="part_id" value="Introductory Library Disc 252/253"/>
			<dataarea name="flop" size="409600">
				<rom name="bitstik1.0_introductory_library.ssd" size="409600" crc="bba2cbdc" sha1="ec73cc3225b3d35285377b143c5d34213a46716d"/>
			</dataarea>
		</part>
	</software>

	<software name="bitstik2">
		<description>Bitstik 2</description>
		<year>1985</year>
		<publisher>Robo Systems</publisher>
		<info name="usage" value="Requires 6502 2nd Processor" />
		<part name="flop1" interface="floppy_5_25">
			<feature name="part_id" value="Introductory Library Disc Vol.1"/>
			<dataarea name="flop" size="204800">
				<rom name="bitstik2.0_library_vol1.ssd" size="204800" crc="2d2ece29" sha1="390fcfee6efb7bf980d1a94dee03db42b8a34cba"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<feature name="part_id" value="Introductory Library Disc Vol.2"/>
			<dataarea name="flop" size="204800">
				<rom name="bitstik2.0_library_vol2.ssd" size="204800" crc="ddda8667" sha1="268799856bd19c06f4a3125d1f4164429d15e0dd"/>
			</dataarea>
		</part>
	</software>

	<software name="coprosup">
		<description>65C102 Co-Processor Support Disc</description>
		<year>1986</year>
		<publisher>Acorn Computers</publisher>
		<info name="format" value="DFS" />
		<info name="usage" value="Requires 65C102 co-processor" />
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="102400">
				<rom name="65C102SupportDisc.ssd" size="102400" crc="f6378bb4" sha1="03bfe9e860ecc6117f2e78771c4e301751269055"/>
			</dataarea>
		</part>
	</software>

	<software name="hisheet">
		<description>Hi-InterSheet</description>
		<year>1986</year>
		<publisher>Computer Concepts</publisher>
		<info name="usage" value="Requires 6502 2nd Processor" />
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="25600">
				<rom name="Hi-InterSheet.ssd" size="25600" crc="276aa20f" sha1="46d80cf02a649d3f43d6ef718b4d7ad03cc95646"/>
			</dataarea>
		</part>
	</software>

	<software name="hiview">
		<description>Hi-View</description>
		<year>1984</year>
		<publisher>Acornsoft</publisher>
		<info name="release" value="SNB15" />
		<info name="usage" value="Requires 6502 2nd Processor" />
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="102400">
				<rom name="Hi-View.ssd" size="102400" crc="f9e79e46" sha1="5b5653c890efc74c3d35d1ab82e51ba43d797346"/>
			</dataarea>
		</part>
	</software>

	<software name="hiwwplus">
		<description>Hi-Wordwise Plus</description>
		<year>1985</year>
		<publisher>Computer Concepts</publisher>
		<info name="usage" value="Requires 6502 2nd Processor" />
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="33280">
				<rom name="Hi-WordWisePlus.ssd" size="33280" crc="e0c88da9" sha1="eeb95137ba5b8428795c552f484b07bf12f2e878"/>
			</dataarea>
		</part>
	</software>

	<software name="l2fsutil">
		<description>Econet Level 2 Fileserver Software</description>
		<year>1985</year>
		<publisher>Acorn</publisher>
		<info name="release" value="AES21" />
		<info name="usage" value="Requires 6502 2nd Processor" />
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="204800">
				<rom name="econet_level_2_utils.ssd" size="204800" crc="c7039167" sha1="37a52b17138c1d84301ed23a04456939810f103c"/>
			</dataarea>
		</part>
	</software>

	<software name="psystem">
		<description>p-System</description>
		<year>1984</year>
		<publisher>Acornsoft/TDI</publisher>
		<info name="release" value="SNB26" />
		<info name="usage" value="Requires 6502 2nd Processor" />
		<part name="flop1" interface="floppy_5_25">
			<feature name="part_id" value="P-System (1)"/>
			<dataarea name="flop" size="204800">
				<rom name="Acornsoft P-System(1).ssd" size="204800" crc="7f880ffb" sha1="2dc9a1905a60e2f40194639c2997e335cfd8a536"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<feature name="part_id" value="P-System (2)"/>
			<dataarea name="flop" size="204800">
				<rom name="Acornsoft P-System(2).ssd" size="204800" crc="c3fe04cc" sha1="cc6b0f42bcd66bafd225b1f2faaefd758266922d"/>
			</dataarea>
		</part>
	</software>

</softwarelist>
